#!/usr/bin/python3
''' Simple script to rename subtitles files with the same name of their
respectives video files allocated in the same directory.
This is very convenient because many video players require it.
You can run it over a single file or other files of directory, with path.
Very useful with TV episodes.
'''

import argparse
import pathlib
import re

__version__ = 'v0.7'
parser = argparse.ArgumentParser(description="Rename subtitles files with the \
    same filename of their respectives video files \
    allocated in the same directory")
parser.add_argument("target", type=str, nargs='+',
                    help="Subtitle file, video file or directory")
parser.add_argument("-v", "--verbose", action="store_true",
                    help="print every file or directories renamed")
parser.add_argument("-n", "--name", type=str, action="store",
                    help="Filter by name")

args = parser.parse_args()
verbose = args.verbose
name = args.name

video_extensions = [
    "mkv",
    "mp4",
    "mov",
]

sub_extensions = [
    "srt",
    "sub"
]

episodes_patterns = [
    r'[sS]([0-9]{1,2})[\.\-_]?[eE]([0-9]{1,2})',
    r'([0-9]{1,2})[xX]([0-9]{1,2})'
]


class Subrenamer(type(pathlib.Path())):
    extensions = {
        "video": video_extensions,
        "sub": sub_extensions
    }
    episodes_patterns = episodes_patterns
    verbose = verbose

    def __init__(self, path=None, *args, **kwargs):
        """Initialize the object"""
        super().__init__()
        self.filter = name
        self.paired = None
        self.tv = {}
        self.type = None
        self.detect_type()

    def run(self):
        """Main workflow. Check if user's argument are a dir or file. Check
        the video extension. If file have an unvalid extension or not exist,
        don't do anything."""
        if self.type == "dir":
            self.dir_mode()
            return True
        if self.type == "video":
            self.pair("sub")
        if self.type == "sub":
            self.pair("video")
        if self.paired:
            self.sub_rename()

    def dir_mode(self):
        """Instantiate a subrenamer object for each file in given dir"""
        for file in self.iterdir():
            if file.is_file():
                file.__init__()
                file.run()

    def detect_episode(self):
        """Check if file is an episode. The filename must have a string that
        matches a pattern defined in episodes_patterns. Like "GoT_S01E03.mkv"
        """
        for pattern in self.episodes_patterns:
            result = re.search(pattern, self.name)
            if result:
                self.tv["season"] = int(result.groups()[0])
                self.tv["episode"] = int(result.groups()[1])
                return True
        return False

    def detect_type(self):
        """check if file have a valid extension of subtitles or videofile
        or is if a directory"""
        if self.is_dir():
            self.type = "dir"
            return True
        if not self.is_file():
            print("{} is not a valid filename or not exists, no action taken".format(
                  self.absolute()))
            return False
        self.detect_episode()
        for type in self.extensions.keys():
            for extension in self.extensions[type]:
                if extension.lower() in self.suffix.lower():
                    self.type = type
                    return True

    def pair(self, type):
        """Find the respective subtitle or video file."""
        for pattern in self.extensions[type]:
            if self.filter:
                files = [file for file in self.parent.glob(
                        "*.{}".format(pattern))
                         if self.filter.lower() in file.name.lower()]
            else:
                files = list(self.parent.glob("*.{}".format(pattern)))
            if not self.tv:
                if len(files) > 1:
                    print("more than one file found, no action taken over {}".
                          format(self.absolute()))
                    return False
                if len(files) == 1:
                    self.paired = files[0]
                    return True
            else:
                for file in files:
                    file.__init__()
                    if (self.tv["episode"] == file.tv["episode"] and
                            self.tv["season"] == file.tv["season"]):
                        self.paired = file
                        return True
                return False

    def print_renamed(self, file):
        """Small function to respect KISS principle in sub_rename method."""
        if self.verbose:
            print("{} renamed".format(file))

    def sub_rename(self):
        """Rename the subtitle with his respective videofile paired if is
        necessary."""
        if self.stem == self.paired.stem:
            if self.verbose:
                print("found files with same name, no action taken over {}".
                      format(self.absolute()))
            return False
        if self.type == "video":
            self.print_renamed(self.paired.absolute())
            self.paired.rename(self.with_suffix(self.paired.suffix))
        if self.type == "sub":
            self.print_renamed(self.absolute())
            self.rename(self.with_name(self.paired.stem + self.suffix))


if __name__ == "__main__":
    for arg in args.target:
        target = Subrenamer(arg)
        target.run()
